export enum WithdrawStatus {
  EMAIL_SENT = 'EMAIL_SENT',
  CANCELLED = 'CANCELLED',
  AWAITING_APPROVAL = 'AWAITING_APPROVAL',
  REJECTED = 'REJECTED',
  PROCESSING = 'PROCESSING',
  FAILURE = 'FAILURE',
  COMPLETED = 'COMPLETED',
}
